version: '3.5'

volumes:
  geonetwork:
  esdata:
  esbackup:
  kibanadata:
  pgdata:
  pglog:
  pgadmindata:
  cantaloupdata:


networks:
  gn-network:
    driver: bridge


services:
  traefik:
    image: traefik:v2.7
    ports:
      - 80:80
      - 443:443
      # Port 8080 is open by default on lal vm
      - 8080:8080
    volumes:
      # First volume needed for Traefik to listen to Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik_config/ssl:/etc/certs:ro
      - ./traefik_config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik_config/traefik-config.yml:/etc/traefik/config.yml:ro
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entryPoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=traefik-strip"
      - "traefik.http.middlewares.traefik-strip.stripprefix.prefixes=/traefik"
      - "traefik.http.routers.traefik.rule=Host(`catalog.geohistoricaldata.org`, `www.catalog.geohistoricaldata.org`) && PathPrefix(`/traefik`) || PathPrefix(`/api`)"
    networks:
      - gn-network


  database:
    image: postgis/postgis:11-2.5
    restart: always
    environment:
      POSTGRES_USER: geonetwork
      POSTGRES_PASSWORD: geonetwork
      POSTGRES_DB: geonetwork
    command: [ "postgres",
               "-c", "log_statement=all",
               "-c", "logging_collector=true",
               "-c", "log_file_mode=0644",
               "-c", "log_directory=/var/log/postgresql",
               "-c", "log_filename=postgresql.log" ]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglog:/var/log/postgresql
    networks:
      - gn-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.database.entryPoints=websecure"
      - "traefik.tcp.routers.database.rule=HostSNI(`*`,`database.catalog.geohistoricaldata.org`)"
      - "traefik.tcp.routers.database.entryPoints=database"
      - "traefik.tcp.routers.database.service=database"
      - "traefik.tcp.services.database.loadbalancer.server.port=5432"
      - "traefik.http.routers.database.tls=true"


  pgadmin4:
    image: dpage/pgadmin4:6.9
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@soduco.com
      PGADMIN_DEFAULT_PASSWORD: admin
      # SCRIPT_NAME needed for "PathPrefix" in traefik
      SCRIPT_NAME: /pgadmin
    # ports need to stay, even with traefik, or it will cause a security error
    ports:
      - 5050:80
    volumes:
      - pgadmindata:/var/lib/pgadmin
    networks:
      - gn-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin4.entryPoints=websecure"
      - "traefik.http.routers.pgadmin4.rule=Host(`catalog.geohistoricaldata.org`, `www.catalog.geohistoricaldata.org`) && PathPrefix(`/pgadmin`)"
      - "traefik.http.routers.pgadmin4.tls=true"


  geonetwork:
    image: geonetwork:4.0.5
    restart: always
    environment:
      DATA_DIR: /catalogue-data

      JAVA_OPTS: >
        -Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
        -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true
        -Xms512M -Xss512M -Xmx2G -XX:+UseConcMarkSweepGC
        -Dgeonetwork.resources.dir=/catalogue-data/resources
        -Dgeonetwork.data.dir=/catalogue-data
        -Dgeonetwork.codeList.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/codelist
        -Dgeonetwork.schema.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins

      ES_HOST: elasticsearch
      ES_PROTOCOL: http
      ES_PORT: 9200

      KB_URL: http://kibana:5601

      GEONETWORK_DB_TYPE: postgres
      GEONETWORK_DB_HOST: database
      GEONETWORK_DB_PORT: 5432
      GEONETWORK_DB_NAME: geonetwork
      GEONETWORK_DB_USERNAME: geonetwork
      GEONETWORK_DB_PASSWORD: geonetwork
    volumes:
      - geonetwork:/catalogue-data
    depends_on:
      - elasticsearch
      - database
    networks:
      - gn-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geonetwork.entryPoints=websecure"      
      - "traefik.http.routers.geonetwork.rule=Host(`catalog.geohistoricaldata.org`, `www.catalog.geohistoricaldata.org`) && PathPrefix(`/geonetwork`)"
      - "traefik.http.routers.geonetwork.tls=true"


  elasticsearch:
    image: elasticsearch:7.9.2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      ES_JAVA_OPTS: "-Xms1G -Xmx1G"
      discovery.type: single-node
      path.repo: "/usr/share/elasticsearch/snapshots"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esbackup:/usr/share/elasticsearch/snapshots
    networks:
      - gn-network


  kibana:
    image: kibana:7.9.2
    environment:
      SERVER_NAME: 'kibana'
      ELASTICSEARCH_URL: http://elasticsearch:9200/
      SERVER_BASEPATH: /geonetwork/dashboards
      SERVER_REWRITEBASEPATH: 'false'
      KIBANA_INDEX: .dashboards
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: 'true'
    networks:
      - gn-network
    volumes:
      - kibanadata:/usr/share/kibana/data


  ontop:
    image: ontop/ontop-endpoint:4.2.0
    restart: unless-stopped
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/catalog.ttl
      ONTOP_MAPPING_FILE: /opt/ontop/input/catalog.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/catalog.properties
      # ONTOP_PORTAL_FILE: /opt/ontop/input/university-complete.portal.toml
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
      ONTOP_LAZY_INIT: "true"
    volumes:
      # files needed by ontop
      - ./ontop_config/input:/opt/ontop/input
      - ./ontop_config/jdbc:/opt/ontop/jdbc
    depends_on:
      - "database"
    networks:
      - gn-network    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ontop.entryPoints=websecure"
      - "traefik.http.routers.ontop.rule=Host(`catalog.geohistoricaldata.org`, `www.catalog.geohistoricaldata.org`) && PathPrefix(`/ontop`)"
      - "traefik.http.routers.ontop.tls=true"
      # - "traefik.http.middlewares.ontop-redirectregex.redirectregex.regex=^https://.*/ontop"
      # - "traefik.http.middlewares.ontop-redirectregex.redirectregex.replacement=https://.*/ontop/$${1}"      
      # - "traefik.http.middlewares.ontop-strip.stripprefix.forceSlash=true"
      - "traefik.http.middlewares.ontop-strip.stripprefix.prefixes=/ontop/"
      - "traefik.http.routers.ontop.middlewares=ontop-strip"


  cantaloupe:
    image: uclalibrary/cantaloupe:5.0.5-1
    restart: unless-stopped
    volumes:
      - ./cantaloupdata:/imageroot
    networks:
      - gn-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cantaloupe.entryPoints=websecure"
      - "traefik.http.routers.cantaloupe.rule=Host(`catalog.geohistoricaldata.org`, `www.catalog.geohistoricaldata.org`)"
      - "traefik.http.routers.cantaloupe.tls=true"
      # - "traefik.http.middlewares.cantaloupe-strip.stripprefix.forceSlash=true"
      # - "traefik.http.middlewares.cantaloupe-strip.stripprefix.prefixes=/cantaloupe/"
      # - "traefik.http.routers.cantaloupe.middlewares=cantaloupe-strip"


  angular-service: # The name of the service
    build: ./geonetwork-ui # Location of our Dockerfile
    volumes: # Volume binding
      - './geonetwork-ui:/usr/src/app'
    networks:
      - gn-network
    depends_on:
      - geonetwork
    command: > 
      bash -c "npm install && ng serve search --host 0.0.0.0 --port 4200"
