# docker-compose build && docker-compose up -d
# If "docker-compose logs ckan" shows DB not ready, run "docker-compose restart ckan" a few times.
version: "3"

volumes:
  ckan_config_test:
  ckan_home_test:
  ckan_storage_test:
  pg_data_test:
  solr_data_test:

networks:
  ckan_network:
    name: ckan_network

services:
  ckan:
    container_name: ckan
    build:
      context: ../../
    links:
      - db
      - solr
      - redis
    depends_on:
      - db
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/ckan
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@db/datastore
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_DATAPUSHER_URL=http://datapusher:8800
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
    restart: unless-stopped
    volumes:
      - ckan_config_test:/etc/ckan
      - ckan_home_test:/usr/lib/ckan
      - ckan_storage_test:/var/lib/ckan
    networks:
      - ckan_network

  datapusher:
    container_name: datapusher
    image: clementmouchet/datapusher
    ports:
      - "8800:8800"
    restart: unless-stopped
    networks:
      - ckan_network

  db:
    container_name: db
    build:
      context: ../../
      dockerfile: contrib/docker/postgresql/Dockerfile  
    environment:
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - pg_data_test:/var/lib/postgresql/data
    networks:
      - ckan_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ckan"]
    restart: unless-stopped

  solr:
    container_name: solr
    build:
      context: ../../
      dockerfile: contrib/docker/solr/Dockerfile
    volumes:
      - solr_data_test:/opt/solr/server/solr/ckan/data
    networks:
      - ckan_network
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:6.2
    networks:
      - ckan_network
    restart: unless-stopped

