global: 
  sendAnonymousUsage: false
  checkNewVersion: false

experimental:
  plugins:
    rewrite:
      modulename: "github.com/traefik/plugin-rewritebody"
      version: "v0.3.1"

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

  database:
    address: ":8080"

providers:
  docker:
    watch: true
    exposedByDefault: false
    endpoint: unix:///var/run/docker.sock

  file:
    filename: /etc/traefik/config.yml
    watch: true

api:
  dashboard: true

log:
  level: INFO
