apiVersion: v1
kind: Service
metadata:
  namespace: dataverse-eu
  labels:
    app: cessda-dataverse-eu-mailrelay-dev
  name: cessda-dataverse-eu-mailrelay-dev
spec:
  ports:
  - name: "smtp"
    port: 25
    targetPort: 25
  selector:
    app: cessda-dataverse-eu-mailrelay-dev
