apiVersion: v1
kind: Service
metadata:
  name: bridge
  namespace: dataverse-eu
  labels:
    component: bridge
spec:
  ports:
  - port: 8592
    targetPort: 8592
    protocol: TCP
    name: api-port
  - port: 9285
    targetPort: 9285
    protocol: TCP
    name: admin-port
  selector:
    component: bridge
    
