version: '3.1'
volumes:
  geonetwork:
      
networks:
  geonetwork_network:
    name: geonetwork_network

services:
  geonetwork:
    image: geonetwork:4.0
    restart: always
    ports:
      - 8080:8080
    environment:
      DATA_DIR: /var/lib/geonetwork_data
      ES_HOST: elasticsearch
      ES_PROTOCOL: http
      ES_PORT: 9200

      # Note: defining the following variable will activate the postgresql
      # configuration and will require an external database (see the database
      # service below)
      POSTGRES_DB_HOST: database

      POSTGRES_DB_NAME: geonetwork
      POSTGRES_DB_USERNAME: geonetwork
      POSTGRES_DB_PASSWORD: geonetwork

    volumes:
      - geonetwork:/var/lib/geonetwork_data
    networks:
      - geonetwork_network
    depends_on:
      - elasticsearch
      - database

  elasticsearch:
    image: elasticsearch:7.6.2
    environment:
      discovery.type: single-node
    networks:
      - geonetwork_network

  database:
    image: mdillon/postgis
    environment:
      POSTGRES_USER: geonetwork
      POSTGRES_PASSWORD: geonetwork
      POSTGRES_DB: geonetwork
    networks:
      - geonetwork_network

